\documentclass[10pt,a4paper,twoside]{article}
\usepackage[numbers]{natbib}
\usepackage{url}
\usepackage{caption}
\usepackage{notoccite}
\usepackage{enumitem}
\usepackage[margin=0.5in]{geometry}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{xcolor}
\usepackage{titlesec}
\usepackage{parskip}
\usepackage{hyperref}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{mathtools}
\usepackage{bm}
\usepackage{dsfont}
\usepackage{bigints}
\usepackage[nointlimits]{esint}
\usepackage{titlesec}
\titleformat*{\section}{\normalsize \bfseries}
\titleformat*{\subsection}{\normalsize \bfseries}
\titlespacing\section{0pt}{10pt}{10pt}
\titlespacing\subsection{0pt}{10pt}{10pt}
\titlespacing\subsubsection{0pt}{10pt}{10pt}
\graphicspath{ {images/} }

\title{\Large \textbf{Experimental Design}}
\author{\large \textbf{Johns Hopkins University}}

\begin{document}
\maketitle
\tableofcontents
\newpage

\section{What does experimental design mean?}

\begin{itemize}
  \item Experimental design is organising an experiment so that we have plentiful and correct data to enable us to clearly and effectively answer the data science question.
  \item The process involves clearly formulating the question before data collection, followed by designing the best possible setup for gathering data, identifying possible sources of error in the design, and only then collecting the appropriate data.
\end{itemize}

\section{Why does the study design matter?}

\begin{itemize}
  \item It is important to plan your analysis in advance to avoid incorrect conclusions. An incorrect analysis can lead to incorrect conclusions.
  \item There is a website called \href{https://retractionwatch.com/}{Retraction Watch} which identifies research papers that have been retracted due to poor scientific practices.
  \item Poor practices often result from poor experimental design and analysis.
  \item Erroneous conclusions can have significant effects, especially in human health.
  \item Example: A retracted paper attempted to predict chemotherapy response based on genome analysis; it was cited nearly 450 times before retraction. Erroneous data then influenced clinical trials for cancer treatment plans.
  \item Proper experimental design is crucial when stakes are high.
\end{itemize}

\section{Principles of experimental design}

There are many concepts and terms inherent to experiment design:

\begin{itemize}
  \item \textbf{Independent variable}: the variable that the experimenter manipulates. The independent variable does not depend on other variables being measured; it is often displayed on the x-axis.
  \item \textbf{Dependent variable}: the variable that is expected to change as a result of changes in the independent variable. The dependent variable is often displayed on the y-axis, so that changes in the independent variable effect changes in the dependent variable.
  \item \textbf{Hypothesis}: an educated guess as to the relationship between the variables and the outcome of the experiment.
\end{itemize}

\subsection{Relationship between variables and hypotheses}

Consider the following example experiment:

\begin{itemize}
  \item Suppose that we hypothesise a positive linear relationship between shoe size and literacy, i.e., we hypothesise that literacy level \emph{depends} on shoe size.
  \item In this experiment, we will take a measure of literacy such as reading fluency as the dependent variable and shoe size as the independent variable.
  \item We design an experiment in which we measure the shoe size and literacy level of 100 individuals.
  \item \textbf{Sample size} is the number of experimental subjects that are included in the experiment. There are many methods to determine the optimal sample size.
\end{itemize}

Before we collect any data, we need to consider if there are problems with this experiment that might cause an erroneous result. In our case, the experiment may be fatally flawed by a \textbf{confounder}:

\begin{itemize}
  \item A \textbf{confounder} is an extraneous variable that may affect the relationship between the dependent and independent variables.
  \item In our example, age also affects foot size, and literacy is affected by age. Thus, observation of a relationship between the two variables may in fact be due to the presence of a confounding variable - age - which ``confounds'' our experimental design.
\end{itemize}

We can control for this situation by taking the following actions:

\begin{itemize}
  \item Measure the age of each individual to account for the effects of age on literacy levels;
  \item Fix the age of all participants, effectively removing the effect of age on literacy.
\end{itemize}

In other experimental design paradigms, a \textbf{control group} may be appropriate:

\begin{itemize}
  \item A control group is a group of experimental subjects that are \emph{not} manipulated.
  \item Example: If we studied the effect of a drug on survival, one group would receive the drug (treatment group) and one group that did not (control group).
  \item This allows us to compare the effects of the drug in the treatment versus control group.
  \item The control group still has their dependent variables measured.
\end{itemize}

In these study designs, there are other strategies we can use to control for confounding effects. For one, we could \textbf{blind} the subjects to their assigned treatment group by giving them a \textbf{placebo}:

\begin{itemize}
  \item A \textbf{placebo} is used in randomised clinical trials to test the efficacy of treatments and is most often used in drug studies. It is a substance or treatment which is designed to have no therapeutic value.
  \item The treatment group receives the actual drug, while the control group receives the placebo.
  \item Participants in both groups do not know if they have received the actual drug or the placebo. This way, researchers can measure if the drug works by comparing how both groups react.
  \item If both groups have the same reaction - improvement or not - the drug is deemed not to work.
\end{itemize}

The above strategy essentially spreads any possible confounding effects equally across the groups being compared. If we assume that age is a possible confounding effect, ensuring that both groups have similar ages and age ranges will help to mitigate any effect that age may cause on the dependent variable, i.e., the effect of age is equal between the two groups.

The balancing of confounders is often achieved by \textbf{randomisation}. Since we do not know what will be a confounder beforehand, we would not want to accidentally risk biasing one group to be enriched for a confounder. To avoid this, we can randomly assign individuals to each of our groups. This means that any potential confounding variables should be distributed between each group roughly equally, to help eliminate/reduce systematic errors.

The type of study described above is called a single-blinded or double-blinded randomised control trial (RCT); single-blind is when the participants of both groups are blinded to the treatment, whereas double-blind is where neither the researchers nor the patients know the treatments being given.

\subsection{Replication}

\textbf{Replication} is one of the key ways in which scientists build confidence in the scientific merit of results. Replication involves repeating the experiment with different experimental subjects. A single experiment's results may have occurred by chance due to factors such as:

\begin{itemize}
  \item A confounder was unevenly distributed across both groups;
  \item There was a systematic error in the data collection;
  \item There were some outliers in the data
\end{itemize}

When the result from one study is found to be consistent by another study, it is more likely to represent a reliable claim to new knowledge. Replication allows you to measure the \textbf{variability} of the data more accurately, which enables us to better assess whether any differences you see in your data are significant.

Replication studies are a great way to bolster your experimental results and calculate the variability in the data. However, a successful replication does not guarantee that the original scientific results of a study were correct, nor does a single failed replication conclusively refute the original claims. A failure to replicate previous results can be due to any number of factors, including:

\begin{itemize}
  \item the discovery of an unknown effect;
  \item inherent variability in the system;
  \item inability to control complex variables;
  \item substandard research practices;
  \item chance/probability.
\end{itemize}

\section{Sharing data}

Once we have collected and analysed our data, one of the next steps is to share the data and code for analysis. GitHub is a great place to share that code, using version controlled data and analyses.

\section{Beware \emph{p}-hacking}

The \textbf{\emph{p}-value} is a commonly reported statistical metric that tells us the probability that the results of the experiment were observed by chance. Something to consider is when you manipulate \emph{p}-values towards your own end. When $p <$ 0.05, there is less than 5$\%$ probability that the differences we observed were by chance, implying that the result is \textbf{significant}. However, if we do 20 tests, by chance, we would expect one of the 20 (5$\%$) to be significant.

In the age of big data, testing 20 hypotheses is a very easy proposition. This is where the term ``\textbf{\emph{p}-hacking}'' originates from. \emph{p}-hacking is when we exhaustively search a dataset to find patterns and correlations that \emph{appear} statistically significant by virtue of the sheer number of tests you have performed. \textbf{These spurious correlations can be reported as significant and if you perform enough tests, you can find a dataset and analysis that will show you what you wanted to see}.

\section{Summary}

We have covered the following topics:

\begin{itemize}
  \item What experimental design is
  \item Why good experimental design matters
  \item Principles of experimental design
  \item Definitions of common terms in experimental design
  \item Importance of sharing data and code for analysis
  \item Dangers of \emph{p}-hacking and manipulating data to achieve significance.
\end{itemize}

\section{Quiz}

\begin{enumerate}
  \item In a study measuring the effect of diet on BMI, cholesterol, lipid levels, triglyceride levels, and glycemic index, which is an independent variable:
    \begin{itemize}
      \item Diet
      \item BMI
      \item Lipid levels
    \end{itemize}
  \item Which of the following is \underline{not} a method to control your experiments?
    \begin{itemize}
      \item Control group
      \item Placebo effect
      \item Blinding
    \end{itemize}
  \item What might a confounder be in an experiment looking at the relationship between the prevalence of white hair in a population and wrinkles?
    \begin{itemize}
      \item Socioeconomic status
      \item Smoking status
      \item Age
    \end{itemize}
  \item According to Leek group recommendations, what data do you need to share with a collaborating statistician?
    \begin{itemize}
      \item The raw data
      \item A tidy data set
      \item A code book describing each variable and its values in the tidy data set.
      \item An explicit and exact recipe of how you went from the raw data to the tidy data and the code book.
      \item All of the above.
    \end{itemize}
  \item If you set your significance level at $p\leq 0.01$, how many significant tests would you expect to see by chance if you carry out 1000 tests?
    \begin{itemize}
      \item 10
      \item 50
      \item 100
    \end{itemize}
  \item What is an experimental design tool that can be used to address variables that may be confounders at the design phase of an experiment?
    \begin{itemize}
      \item Stratifying variables
      \item Data cleaning
      \item Using all the data you have access to
    \end{itemize}
  \item Which of the following describes a descriptive analysis?
    \begin{itemize}
      \item Use your sample data distribution to make predictions for the future
      \item Draw conclusions from your sample data distribution and infer for the larger population
      \item Generate a table summarising the number of observations in your dataset as well as the central tendencies and variances of each variable.
    \end{itemize}
\end{enumerate}





\end{document}
