---
title: "Regression Models"
author: "Hiten Pragji"
date: "`r format(Sys.Date(), '%d-%m-%Y')`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    latex_engine: xelatex
geometry: margin=0.75in
fontsize: 10pt
header-includes:
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{graphicx}
  - \usepackage[numbers]{natbib}
  - \usepackage{url}
  - \usepackage{caption}
  - \usepackage{notoccite}
  - \usepackage{enumitem}
  - \usepackage{caption}
  - \usepackage{xcolor}
  - \usepackage{titlesec}
  - \usepackage{parskip}
  - \usepackage{hyperref}
  - \usepackage{mathtools}
  - \usepackage{bm}
  - \usepackage{dsfont}
  - \usepackage{bigints}
  - \usepackage[nointlimits]{esint}
  - \usepackage{titlesec}
  - \titleformat*{\section}{\large\bfseries}
  - \titleformat*{\subsection}{\normalsize\bfseries}
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

\clearpage

\section{Introduction}

\begin{itemize}
  \item \textbf{Linear models}
    \begin{itemize}[leftmargin=*]
      \item Linear regression
      \item Polynomial regression
      \item Ridge regression
      \item Lasso regression
    \end{itemize}
  \item \textbf{Generalised linear models}
    \begin{itemize}[leftmargin=*]
      \item Logistic regression
      \item Poisson regression
    \end{itemize}
  \item \textbf{Non-linear parametric models}
  \item \textbf{Non-parametric models}
\end{itemize}

\section{Linear regression}

Regression is a supervised machine learning method by which we can determine the existence and strength of the relationship between two or more variables. In particular, linear regression is a useful tool for predicting an quantitative response. Broadly, there are often two separate goals in regression:

\begin{itemize}[leftmargin=*]
  \item Prediction: fitting a model to observed data to predict outcomes for new observations;
  \item Inference: fitting a model to estimate and interpret the relationships between variables.
\end{itemize}

A clear scientific question should define our explanatory variable of interest ($x$), which is referred to as a predictor or independent variable. Our outcome of interest is referred to as the dependent variable or outcome ($y$). In linear regression, the dependent variable is always continuous; it cannot be a categorical variable. The explanatory variables can be either continuous or categorical.

Here are some examples of real-world regression problems:

\begin{itemize}[leftmargin=*]
  \item Predict tomorrow's stock market price given current market conditions and other possible side information;
  \item Predict the temperature at any location inside a building using weather data, time, door sensors, etc.;
  \item Predict systolic blood pressure based on the number of cups of coffee consumed per day;
  \item Predict the fuel efficiency of a car given engine parameters, speed, and road conditions;
  \item Predict daily electricity consumption in a household based on appliance usage, weather, and time of day;
\end{itemize}

\subsection{Simple linear regression}

Simple linear regression, or univariate linear regression, is a very straightforward approach for predicting a quantitative response $Y$ on the basis of a single predictor variable $X$. It assumes that there is approximately a linear relationship between $X$ and $Y$. Mathematically, we can write this linear relationship as

\begin{align}
  Y \approx \beta_{0} + \beta_{1}X
\end{align}

where the *intercept* $\beta_{0}$ (value of $y(x = 0)$) and *slope* $\beta_{1}$ (predicted increase in $y$ for a unit increase in $x$) are unknown constants known as the model coefficients or parameters. Once we have used our training data to produce estimates  $\hat{\beta_{0}}$ and $\hat{\beta_{1}}$ for the model coefficients, we can predict an outcome on the basis of a particular value of the predictor variable by computing

\begin{align}
  \hat{y} = \hat{\beta_{0}} + \hat{\beta_{1}}x,
\end{align}

where $\hat{y}$ indicates a prediction of $Y$ on the basis of $X = x$. Here we use a *hat* symbol to denote the estimated value for an unknown parameter or coefficient, or to denote the predicted value of the response.

\subsubsection{Estimating the coefficients}

In practice, the true values of the population parameters $\beta_{0}$ and $\beta_{1}$, so before we can use Equation (1) to make predictions, we must use data to *estimate* the coefficients. Suppose we have the following $n$ observation pairs:

\begin{align}
  (x_{1}, y{1}), (x_{2}, y_{2}), ..., (x_{n}, y_{n})
\end{align}

each of which consists of a measurement of $X$ and a measurement of $Y$. Our goal is to obtain coefficient estimates $\hat{\beta_{0}}$ and $\hat{\beta_{1}}$ such that the linear model (Equation 1) fits the available data well. In R, the `lm()` function finds the `best' coefficients $\hat{\beta_{0}}$ and $\hat{\beta_{1}}$ where the *fitted values* (or expected values) are given by

\begin{align}
  \hat{y}_{i} = \hat{\beta_{0}} + \hat{\beta_{1}}x_{i},
\end{align}

In other words, we want to find an intercept $\hat{\beta_{0}}$ and a slope $\hat{\beta_{1}}$ such that the resulting line is as close as possible to the $n$ data points. The best-fitting regression line is usually determined by minimising the *least squares* criterion, 

\subsection{Multiple linear regression}


















